#!/bin/sh
volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F'[:/]' '/Volume:/{print $4}' | tr -d ' %')
is_muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [ "$is_muted" = "yes" ]
then
   volume=0
fi

if [ "$volume" -gt 75 ]
then
   emoji="🔊"
elif [ "$volume" -gt 50 ]
then
   emoji="🔉"
elif [ "$volume" -eq 0 ]
then
   emoji="🔇"
   sudo hda-verb /dev/snd/hwC1D0 0x20 0x500 0x0B && sudo hda-verb /dev/snd/hwC1D0 0x20 0x400 0x7778
else
   emoji="🔈"
   sudo hda-verb /dev/snd/hwC1D0 0x20 0x500 0x0B && sudo hda-verb /dev/snd/hwC1D0 0x20 0x400 0x7774
fi

echo "$emoji $volume%"
